// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01.Net_Core_Restful_API.Data;

namespace _01.Net_Core_Restful_API.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20210520112445_AddCompanyBankruptTime")]
    partial class AddCompanyBankruptTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("_01.Net_Core_Restful_API.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BankruptTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84c8ff0a-90a7-4f54-b47b-4c933f4f2115"),
                            Country = "America",
                            Industry = "Android",
                            Introduction = "Great Company",
                            Name = "Google",
                            Product = "Google Chrome Browser"
                        },
                        new
                        {
                            Id = new Guid("5001e311-51d2-469f-8446-ba5364155f29"),
                            Country = "America",
                            Industry = "PC System",
                            Introduction = "Don't be evil",
                            Name = "Microsoft",
                            Product = "Office 365"
                        },
                        new
                        {
                            Id = new Guid("5313d3dc-874c-4b46-a8b8-2018923213fb"),
                            Country = "China",
                            Industry = "Internet",
                            Introduction = "TaoBao Company",
                            Name = "Alipapa",
                            Product = "AliPay"
                        },
                        new
                        {
                            Id = new Guid("b3a3a73e-88c0-4c94-af92-c9d11b0a8b9c"),
                            Country = "China",
                            Industry = "Short Video",
                            Introduction = "Tik Tok",
                            Name = "ByteDance",
                            Product = "Tik Tok"
                        },
                        new
                        {
                            Id = new Guid("1a805447-13db-41c8-861e-370942215b96"),
                            Country = "China",
                            Industry = "Mobile Phone",
                            Introduction = "Mobile Phone Company",
                            Name = "XIOAMI",
                            Product = "Xiao Mi 11"
                        },
                        new
                        {
                            Id = new Guid("f322d130-6e24-477e-8f49-684bfc681211"),
                            Country = "China",
                            Industry = "Safe Software",
                            Introduction = "Software Company",
                            Name = "360",
                            Product = "360"
                        },
                        new
                        {
                            Id = new Guid("50d80f33-844d-4d28-9504-7e541719ff36"),
                            Country = "China",
                            Industry = "Social APP,Game",
                            Introduction = "Game Company",
                            Name = "Tencent",
                            Product = "WeChat,QQ"
                        },
                        new
                        {
                            Id = new Guid("423d5d98-a496-44d8-8008-bc0b9c40fd80"),
                            Country = "China",
                            Industry = "Live",
                            Introduction = "Live WebSite",
                            Name = "Douyu",
                            Product = "Douyu Live"
                        },
                        new
                        {
                            Id = new Guid("b230f808-1cad-47ea-a484-68ccb3d53154"),
                            Country = "America",
                            Industry = "Social",
                            Introduction = "Social App",
                            Name = "Twitter",
                            Product = "Twitter"
                        },
                        new
                        {
                            Id = new Guid("f337a186-d3f0-4809-b2e7-f9370b129e61"),
                            Country = "America",
                            Industry = "Rocket,Electric Car",
                            Introduction = "Rocket,Electric Car",
                            Name = "SpaceX",
                            Product = "Tesla"
                        },
                        new
                        {
                            Id = new Guid("431c949b-7b83-46ac-943b-d4e773495041"),
                            Country = "China",
                            Industry = "Delivery",
                            Introduction = "Take away",
                            Name = "MeiTuan",
                            Product = "Mei Tuan App"
                        });
                });

            modelBuilder.Entity("_01.Net_Core_Restful_API.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07389c3c-ac3e-46f9-b6bd-5320b7eb326d"),
                            CompanyId = new Guid("84c8ff0a-90a7-4f54-b47b-4c933f4f2115"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "cm20210001",
                            FirstName = "Nick",
                            Gender = 1,
                            LastName = "Brand"
                        },
                        new
                        {
                            Id = new Guid("5e23cc44-50f3-4ef7-976b-92e0991899b8"),
                            CompanyId = new Guid("84c8ff0a-90a7-4f54-b47b-4c933f4f2115"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "cm20210002",
                            FirstName = "Vince",
                            Gender = 2,
                            LastName = "John"
                        },
                        new
                        {
                            Id = new Guid("a9061730-7868-4869-9f96-f17d5ac97690"),
                            CompanyId = new Guid("84c8ff0a-90a7-4f54-b47b-4c933f4f2115"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "cm20210003",
                            FirstName = "Bryant",
                            Gender = 1,
                            LastName = "Kobbo"
                        });
                });

            modelBuilder.Entity("_01.Net_Core_Restful_API.Entities.Employee", b =>
                {
                    b.HasOne("_01.Net_Core_Restful_API.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("_01.Net_Core_Restful_API.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
